site_name: "Vibe Coding Hackathon Docs"
site_description: "Documentation and submissions for the 2025 Vibe Coding Hackathon"
site_author: "NYU Vibe Coding Hackathon"
docs_dir: docs-md
site_dir: docs

nav:
  - Docs: index.md
  - Submissions:
      - Overview: submissions.md
      - Performance & Functionality: submissions/performance-and-functionality.md
      - Prompts: submissions/prompts.md
  - Rubric: rubric.md

theme:
  logo: assets/images/favicon.png
  features:
  - navigation.footer
  - search.highlight
  name: material
  palette:
    primary: indigo
    accent: indigo
plugins: []
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
