site_name: "Vibe Coding Hackathon Docs"
site_description: "Documentation and submissions for the 2025 Vibe Coding Hackathon"
site_author: "NYU Vibe Coding Hackathon"

nav:
  - Docs: index.md
  - Submissions:
      - Overview: submissions.md
      - Performance & Functionality: submissions/performance-and-functionality.md
      - Prompts: submissions/prompts.md
  - Rubric: rubric.md

theme:
  logo: assets/readme_assets/tiny_spid.png
  features:
  - navigation.footer
  - search.highlight
  name: material
  palette:
    primary: light green
    accent: lime
plugins: []
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/nyuvibecode/nyuvibecode.github.io 
